MetlifeAdminPanel/Controllers/D2CReportingController.cs
using MetlifeAdminPanel.Models;
using MetlifeAdminPanel.Services;
using RKLib.ExportData;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace MetlifeAdminPanel.Controllers
{
    public class D2CReportingController : Controller
    {
        List<DisplayTable> listPaymentType = DBContext.GetPaymentTypeList();
        List<DisplayTable> listPaymentGateways = DBContext.GetPaymentGateways();
        public static string downloadedFileName = "";
        Enc enc1 = new Enc();
        private OLPABDDATAEntities_new db = new OLPABDDATAEntities_new();


        string path = AppDomain.CurrentDomain.BaseDirectory + "Downloaded";
        string NewPath = ConfigurationManager.AppSettings["FTP_LOCATION_D2C"]; 

        public ActionResult Search()
        {
            if (!DBContext.hasPermission("MetLife D2C Report"))
            {
                return RedirectToAction("Action", "Error");
            }
            else
            {
                ReportManagerD2C reportManager = new ReportManagerD2C();
                reportManager.dummySearch.DropDownListForPaymentType = new SelectList(listPaymentType, "Key", "Display");
                reportManager.dummySearch.DropDownListForGateways = new SelectList(listPaymentGateways, "Key", "Display");

                return View(reportManager);
            }
        }

        [HttpPost]
        public ActionResult Search(ReportManagerD2C reportManager)
        {
            if (!DBContext.hasPermission("MetLife D2C Report"))
            {
                return RedirectToAction("Action", "Error");
            }
            else
            {
                List<D2C_Transaction_Log> list = DBContext.GetD2CLog(reportManager);
                reportManager.tranList = list;
                reportManager.dummySearch.DropDownListForPaymentType = new SelectList(listPaymentType, "Key", "Display");
                reportManager.dummySearch.DropDownListForGateways = new SelectList(listPaymentGateways, "Key", "Display");
                return View(reportManager);
            }
        }

        public ActionResult DownloadReport()
        {
            if (!DBContext.hasPermission("MetLife D2C Report"))
            {
                return RedirectToAction("Action", "Error");
            }
            else
            {
                ReportManagerD2C reportManager = new ReportManagerD2C();
                reportManager.dummySearch.DropDownListForPaymentType = new SelectList(listPaymentType, "Key", "Display");
                reportManager.dummySearch.DropDownListForGateways = new SelectList(listPaymentGateways, "Key", "Display");

                return RedirectToAction("search");
                //return View("search", reportManager);
            }
        }
        [HttpPost]
        public ActionResult DownloadReport(ReportManagerD2C reportManager)
        {

            if (!DBContext.hasPermission("MetLife D2C Report"))
            {
                return RedirectToAction("Action", "Error");
            }
            else
            {
                Enc enc = new Enc();
                List<D2C_Transaction_Log> list = DBContext.GetD2CLog(reportManager);
                reportManager.tranList = list;
                reportManager.dummySearch.DropDownListForPaymentType = new SelectList(listPaymentType, "Key", "Display");
                reportManager.dummySearch.DropDownListForGateways = new SelectList(listPaymentGateways, "Key", "Display");
                List<ExcelDataD2C> list2 = new List<ExcelDataD2C>();
                foreach (D2C_Transaction_Log trn in list.Where(w => w.ExcelDownload != 1))
                {
                    ExcelDataD2C trn2 = new ExcelDataD2C();
                    //"SLNO OF DAY", "TRANSACTION NO", "TRANDATE & TIME", "PAID FOR",
                    //    "PAID FOR DETAIL", "POLICY NO", "PAID AMT", "ACK SENT", "PO NAME", 
                    //    "AGENT CODE", "EMAIL ID", "BRAND OF CARD", "CBL/BKS REF NO", "CLIENT NAME"

                    if (trn.SerialOfDay != null)
                    {
                        trn2.SerialOfDay = trn.SerialOfDay;
                    }
                    if (trn.TransactionNo != null)
                    {
                        trn2.TransactionNo = trn.TransactionNo.ToString();
                    }
                    if (trn.PaymentDate != null)
                    {
                        trn2.PaymentDate = trn.PaymentDate.ToString();
                    }
                    if (trn.PaidFor != null)
                    {
                        trn2.PaidFor = trn.PaidFor;
                    }
                    if (trn.ApplicationType != null)
                    {
                        trn2.ApplicationType = trn.ApplicationType;
                    }
                    
                    if (trn.PolicyNumber != null)
                    {
                        trn2.PolicyNumber = trn.PolicyNumber;
                    }
                    if (trn.Amount != null)
                    {
                        trn2.Amount = trn.Amount;
                    }
                    if (trn.Status != null)
                    {
                        trn2.Status = trn.Status;
                    }
                    if (trn.POName != null)
                    {
                        trn2.POName = trn.POName;
                    }
                    if (trn.AgentCode != null)
                    {
                        trn2.AgentCode = trn.AgentCode;
                    }
                    if (trn.PayerEmail != null)
                    {
                        trn2.PayerEmail = trn.PayerEmail;
                    }
                    if (trn.BOCard != null)
                    {
                        trn2.BOCard = trn.BOCard;
                    }
                    if (trn.GatewayTransactionID != null)
                    {
                        trn2.GatewayTransactionID = trn.GatewayTransactionID;
                    }
                    if (trn.ClientName != null)
                    {
                        trn2.ClientName = trn.ClientName;
                    }
                    list2.Add(trn2);
                    D2C_Transaction_Log transactionToUpdate = db.D2C_Transaction_Log.Where(m => m.Id == trn.Id).Single();
                    if (transactionToUpdate != null)
                    {
                        Update(transactionToUpdate);
                    }
                }

                if (list2.Count != 0)
                {
                    try
                    {
                        DataSet dataSet = ReportManager.ListToDataSet(list2);
                        DataTable dtReport = dataSet.Tables["Table1"].Copy();
                        RKLib.ExportData.Export objExport = new RKLib.ExportData.Export("Win");

                        downloadedFileName = "Metlife_D2C_Log_Report_" + DateTime.Now.Year + DateTime.Now.Month + DateTime.Now.Day + DateTime.Now.Hour + DateTime.Now.Minute + DateTime.Now.Second + DateTime.Now.Millisecond + "_" + reportManager.dummySearch.gateways + ".xls";

                        //string[] columnNames = { "Application Type", "Policy Number", "Amount", "Grand Amount", "Payer Email", "Payment Date", "Status", "Gateway TransactionID", "PO NAME", "PO Mobile", "ClientName" };
                        //int[] a = { 0, 1,2, 3, 4, 5, 6, 8, 9, 10 };


                        //string[] columnNames = { "Application Type", "Policy Number", "Amount", "Grand Amount", "Payer Email", "Payment Date", "Status", "Gateway TransactionID", "PO NAME", "PO Mobile", "ClientName" };
                        //int[] a = { 0,1,2,3,4,5,6,7,8,9,10};

                        string[] columnNames = { "SLNO OF DAY", "TRANSACTION NO", "TRANDATE & TIME", "PAID FOR", "PAID FOR DETAIL", "POLICY NO", "PAID AMT", "ACK SENT", "PO NAME", "AGENT CODE", "EMAIL ID", "BRAND OF CARD", "CBL/BKS REF NO", "CLIENT NAME" };
                        int[] a = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13};

                        objExport.ExportDetails(dtReport, a, columnNames, Export.ExportFormat.Excel, path + downloadedFileName);


                       
                        objExport.ExportDetails(dtReport, a, columnNames, Export.ExportFormat.Excel, NewPath + downloadedFileName);

                        savelog("Mail Send Starting", true);
                        SendDownloadEmail();
                        return RedirectToAction("DownloadFile", new { fileName = downloadedFileName, filecount = list2.Count });

                    }
                    catch (Exception Ex)
                    {
                      
                    }

                }
                if (list2.Count == 0)
                {
                    return RedirectToAction("Index", "Message");
                }
                else
                {
                    return View("search", reportManager);
                }

            }
        }

        public ActionResult DownloadFile(string fileName, string filecount)
        {
            byte[] fileBytes = System.IO.File.ReadAllBytes(path + fileName);
            ModelState.AddModelError("Success", "Downloaded successfully");

            //SendInvoiceEmail(filecount);

            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
        }

        public void Update(D2C_Transaction_Log trx)
        {
            if (DBContext.hasPermission("MetLife D2C Report"))
            {

                trx.ExcelDownload = 1;
              
                if (ModelState.IsValid)
                {
                    db.Entry(trx).State = EntityState.Modified;
                    db.SaveChanges();
                }
            }
        }
        public EmailSetting GetEmailInformation()
        {

MetlifeAdminPanel/Views/D2CReporting/Search.cshtml
@model MetlifeAdminPanel.Services.ReportManagerD2C
@using MetlifeAdminPanel.Services
@{
    ViewBag.Title = "Search";
}

<div class="row">
    <div class="col-sm-12">
        <div class="white-box">
            @if (TempData["failed"] != null)
            {
                <img src="~/Content/my_style/plugins/images/failed.jpg" width="30" height="30">
                <span style="color: red; font-size:large; " role="alert">
                    @TempData["failed"]
                </span>
                <br />
            }
            @if (TempData["success"] != null)
            {
                <img src="~/Content/my_style/plugins/images/ok.jpg" width="50" height="50">
                <span style="color: green; font-size:large;" role="alert">
                    @TempData["success"]
                </span>
                <br />
            }
            @using (Html.BeginForm("Search", "D2CReporting", FormMethod.Post, new { autocomplete = "off", enctype = "multipart/form-data", @class = "form-material form-horizontal m-t-30", @id = "search-form" }))
            {
                @Html.AntiForgeryToken()

                @Html.ValidationSummary(true)

                <div class="row">
                    <div class="col-md-3">
                        <label class="col-sm-12">Payment From Date</label>
                        <input type="text" id="datepicker" class="form-control" name="dummySearch.startDate" value="@Model.dummySearch.startDate">
                        @Html.ValidationMessageFor(model => model.dummySearch.startDate)
                    </div>
                    <div class="col-md-3">
                        <label class="col-sm-12">Payment To Date</label>
                        <input type="text" id="datepicker" class="form-control" name="dummySearch.endDate" value="@Model.dummySearch.endDate">
                        @Html.ValidationMessageFor(model => model.dummySearch.endDate)
                    </div>
                    <div class="col-md-3">
                        <label class="col-sm-12">Policy Number</label>
                        <input type="text" class="form-control" name="dummySearch.policyNumber" value="@Model.dummySearch.policyNumber">
                        @Html.ValidationMessageFor(model => model.dummySearch.policyNumber)
                    </div>
                    @*<div class="col-md-3">
                            <label class="col-sm-12">Type</label>
                            @Html.DropDownListFor(model => model.dummySearch.type, Model.dummySearch.DropDownListForPaymentType, "Select a Payment Mode", new { @class = "form-control" })
                        </div>*@

                    <div class="col-md-3">
                        <label class="col-sm-12">Payment Channel</label>
                        @*@Html.DropDownListFor(model => model.dummySearch.gateways, Model.dummySearch.DropDownListForGateways, "Select a Payment Channel", new { @class = "form-control" })*@

                        <select class="form-control" id="downloadStatus" name="dummySearch.gateways">
                            @*<option value="All" @("All" == @Model.dummySearch.gateways ? "selected" : "")>Select a Payment Channel </option>*@


                            <option value="Bkash" @("Bkash" == @Model.dummySearch.gateways ? "selected" : "")>Bkash</option>

                        </select>

                    </div>
                </div>


                <div class="row">
                    <div class="col-md-12 m-t-30">
                        <button type="submit" class="btn btn-info waves-effect waves-light m-r-10">Search</button>

                    </div>
                </div>
            }
            @*</form>*@
            @if (Model.tranList != null)
            {
                if (Model.tranList.Count > 0)
                {
                    <div class="col-sm-12">
                        <div class="white-box">
                            <div class="table-responsive">
                                <table id="example" class="table display">
                                    <thead>
                                        <tr>

                                            <th>
                                                ID
                                            </th>
                                            <th>
                                                MetTran ID
                                            </th>
                                            <th>
                                                ApplicationType
                                            </th>
                                            <th>
                                                PolicyNumber
                                            </th>
                                            <th>
                                                Amount
                                            </th>
                                            <th>
                                                GrandAmount
                                            </th>
                                            <th>
                                                PayerEmail
                                            </th>

                                            <th>
                                                PaymentDate
                                            </th>
                                            <th>
                                                Status
                                            </th>
                                            <th>
                                                GatewayTransactionID
                                            </th>
                                            <th>
                                                POName
                                            </th>
                                            <th>
                                                POMobile
                                            </th>
                                            <th>
                                                ClientName
                                            </th>
                                            <th>
                                                Sl Day
                                            </th>
                                            <th>
                                                ExcelDownload
                                            </th>

                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model.tranList)
                                        {
                                        <tr>
                                            <td>@item.Id</td>
                                            <td>@item.TransactionNo</td>
                                            <td>@item.ApplicationType</td>
                                            <td>@item.PolicyNumber</td>
                                            <td>@item.Amount</td>
                                            <td>@item.GrandAmount</td>
                                            <td>@item.PayerEmail</td>
                                            <td>@item.PaymentDate</td>
                                            <td>@item.Status</td>
                                            <td>@item.GatewayTransactionID  </td>
                                            <td>@item.POName</td>
                                            <td>@item.POMobile</td>
                                            <td>@item.ClientName</td>
                                            <td>@item.SerialOfDay</td>
                                            <td>@item.ExcelDownload</td>
                                        </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                            <br />
                            @using (Html.BeginForm("DownloadReport", "D2CReporting", FormMethod.Post, new { autocomplete = "off", enctype = "multipart/form-data", @class = "form-material form-horizontal m-t-30" }))
                            {
                                
               
                                
                                <input type="hidden" name="dummySearch.startDate" value="@Model.dummySearch.startDate">
                                <input type="hidden" name="dummySearch.endDate" value="@Model.dummySearch.endDate">
                                @*<input type="hidden" name="dummySearch.type" value="@Model.dummySearch.type">*@
                                <input type="hidden" name="dummySearch.policyNumber" value="@Model.dummySearch.policyNumber">
                                <input type="hidden" name="dummySearch.downloadStatus" value="@Model.dummySearch.downloadStatus">
                                <input type="hidden" name="dummySearch.status" value="@Model.dummySearch.status">
                                <input type="hidden" name="dummySearch.gateways" value="@Model.dummySearch.gateways">

                                <div class="row">
                                    <div class="col-md-12 m-t-30">
                                        <button type="submit" class="btn btn-info waves-effect waves-light m-r-10">Download Excel</button>
                                    </div>
                                    <br />

                                    @if (Html.ValidationMessage("Error") != null)
                                    {
                                        <span style="color: red; font-size:large; " role="alert">
                                            @Html.ValidationMessage("Error")
                                        </span>
                                    }
                                    @if (Html.ValidationMessage("Success") != null)
                                    {
                                        <span style="color: green; font-size:large;" role="alert">
                                            @Html.ValidationMessage("Success")
                                        </span>
                                    }
                                </div>
                                @*</form>*@
                            }
                        </div>
                    </div>



                }
                else
                {
                    <p>No Data Found</p>
                }

            }


            @*@Html.ActionLink("Click here to download", "DownloadFile", new { })*@
        </div>
    </div>
</div>
<script>

    jQuery(document).ready(function () {
        $("#manual-in-out2").addClass('collapse in');
        $("#manual-in-out6").addClass('collapse in');

        $("#d2c-report-id").addClass('active');
    });

</script>