MetlifeAdminPanel/Controllers/ErrorListController.cs
using MetlifeAdminPanel.Services;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MetlifeAdminPanel.Controllers
{
    public class ErrorListController : Controller
    {
        private OLPABDDATAEntities_new db = new OLPABDDATAEntities_new();

        //
        // GET: /ErrorList/

        public ActionResult Index()
        {
            if (!DBContext.hasPermission("Metlife Error Management"))
            {
                return RedirectToAction("Action", "Error");
            }
            else
            {
                return View(db.ErrorLists.ToList());
            }
        }

        //
        // GET: /ErrorList/Details/5

        public ActionResult Details(int id = 0)
        {
            if (!DBContext.hasPermission("Metlife Error Management"))
            {
                return RedirectToAction("Action", "Error");
            }
            else
            {
                ErrorList errorlist = db.ErrorLists.Find(id);
                if (errorlist == null)
                {
                    return HttpNotFound();
                }
                return View(errorlist);
            }
        }

        //
        // GET: /ErrorList/Create

        public ActionResult Create()
        {
            if (!DBContext.hasPermission("Metlife Error Management"))
            {
                return RedirectToAction("Action", "Error");
            }
            else
            {
                return View();
            }
        }

        //
        // POST: /ErrorList/Create

        [HttpPost]
        public ActionResult Create(ErrorList errorlist)
        {
            if (!DBContext.hasPermission("Metlife Error Management"))
            {
                return RedirectToAction("Action", "Error");
            }
            else
            {
                errorlist.CreationTime = DateTime.Now;
                if (ModelState.IsValid)
                {
                    db.ErrorLists.Add(errorlist);
                    db.SaveChanges();
                    TempData["success"] = "Error created successfully";
                    return RedirectToAction("Index");
                }
                else {
                    TempData["failed"] = "Error registration failed";               
                }
                return View(errorlist);
            }
        }

        //
        // GET: /ErrorList/Edit/5

        public ActionResult Edit(int id = 0)
        {
            if (!DBContext.hasPermission("Metlife Error Management"))
            {
                return RedirectToAction("Action", "Error");
            }
            else
            {
                ErrorList errorlist = db.ErrorLists.Find(id);
                if (errorlist == null)
                {
                    return HttpNotFound();
                }
                return View(errorlist);
            }
        }

        //
        // POST: /ErrorList/Edit/5

        [HttpPost]
        public ActionResult Edit(ErrorList errorlist)
        {
            if (!DBContext.hasPermission("Metlife Error Management"))
            {
                return RedirectToAction("Action", "Error");
            }
            else
            {
                errorlist.UpdateTime = DateTime.Now;
                if (ModelState.IsValid)
                {
                    db.Entry(errorlist).State = EntityState.Modified;
                    db.SaveChanges();
                    TempData["success"] = "Error updated successfully";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["failed"] = "Error update failed";
                }
                return View(errorlist);
            }
        }

        //
        // GET: /ErrorList/Delete/5

        public ActionResult Delete(int id = 0)
        {
            if (!DBContext.hasPermission("Metlife Error Management"))
            {
                return RedirectToAction("Action", "Error");
            }
            else
            {
                ErrorList errorlist = db.ErrorLists.Find(id);
                if (errorlist == null)
                {
                    return HttpNotFound();
                }
                return View(errorlist);
            }
        }

        //
        // POST: /ErrorList/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            if (!DBContext.hasPermission("Metlife Error Management"))
            {
                return RedirectToAction("Action", "Error");
            }
            else
            {
                ErrorList errorlist = db.ErrorLists.Find(id);
                db.ErrorLists.Remove(errorlist);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MetlifeAdminPanel/Views/ErrorList/Create.cshtml
@model MetlifeAdminPanel.ErrorList

@{
    ViewBag.Title = "Error Form";
}


<div class="row">					
	<div class="col-sm-12">
        <div class="white-box">
           @if(TempData["failed"] != null)
           {
			    <img src="~/Content/my_style/plugins/images/failed.jpg" width="30" height="30">
			    <span  style="color: red; font-size:large; "  role="alert" >
					    @TempData["failed"]						
			    </span>
			    <br/>
		    }									 
		    @if(TempData["success"] != null)
            {
			    <img src="~/Content/my_style/plugins/images/ok.jpg" width="50" height="50">
			    <span  style="color: green; font-size:large;"  role="alert" >
					    @TempData["success"] 							
			    </span>
			    <br/>				
		    }  
            @using (Html.BeginForm("Create", "ErrorList", FormMethod.Post, new { autocomplete = "off", enctype = "multipart/form-data", @class = "form-material form-horizontal m-t-30"}))
            {
                @Html.AntiForgeryToken()
             @*<form action="/ErrorList/Create" method="post" class="form-material form-horizontal m-t-30"> *@
                @Html.ValidationSummary(true)
                   <div class="row">
                      <div class="col-sm-3">
                        <label class="col-sm-12">Error Code</label>
                        <input type="text" class="form-control" name ="ErrorCode" required ="required">
                         @Html.ValidationMessageFor(model => model.ErrorCode)
                      </div>
                   </div>
                   <div class="row">                   
                      <div class="col-md-3">
                        <label class="col-sm-12">Summary</label>
                        <textarea class="form-control" name ="Summary" cols="60" rows="5"> </textarea> 
                        @Html.ValidationMessageFor(model => model.Summary)
                     </div>
                  </div>
                   <div class="row">
                      <div class="col-sm-3">
                        <label class="col-sm-12">Message</label>
                        <input type="text" class="form-control" name ="Message" required ="required">
                         @Html.ValidationMessageFor(model => model.Message)
                      </div>
                   </div>
                  <div class="row">
                      <div class="col-md-12 m-t-30">    
                        <button type="submit" class="btn btn-info waves-effect waves-light m-r-10">Submit</button>
                        <button type="reset" class="btn btn-inverse waves-effect waves-light">Reset</button>
                      </div>
                  </div>
                 <h4>To Show list of Error @Html.ActionLink("click here", "Index")</h4>
            }
            @*</form>*@
        </div>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
    <script>
        $(document).ready(function () {
            $("#manual-in-out2").addClass('collapse in');
            $("#manual-in-out7").addClass('collapse in');

            $("#err-id").addClass('active');
        });
    </script>

MetlifeAdminPanel/Views/ErrorList/Delete.cshtml
@model MetlifeAdminPanel.ErrorList

@{
    ViewBag.Title = "Delete Error";
}


<div class="row">					
   <div class="col-sm-12">
     <div class="white-box">
           @if(TempData["failed"] != null)
           {
			    <img src="~/Content/my_style/plugins/images/failed.jpg" width="30" height="30">
			    <span  style="color: red; font-size:large; "  role="alert" >
					    @TempData["failed"]						
			    </span>
			    <br/>
		    }									 
		    @if(TempData["success"] != null)
            {
			    <img src="~/Content/my_style/plugins/images/ok.jpg" width="50" height="50">
			    <span  style="color: green; font-size:large;"  role="alert" >
					    @TempData["success"] 							
			    </span>
			    <br/>				
		    }  
            @using (Html.BeginForm("Delete", "ErrorList", FormMethod.Post, new { autocomplete = "off", enctype = "multipart/form-data", @class = "form-material form-horizontal m-t-30"}))
            {
                @Html.AntiForgeryToken()
            @*<form action="#" method="post" class="form-material form-horizontal m-t-30">*@ 
            @Html.HiddenFor(model => model.Id)
            <div class="row">
                <div class="col-sm-3">
                    <label class="col-sm-12">Error Code</label>
                    <input type="text" class="form-control" value="@Html.DisplayFor(model => model.ErrorCode)"  readonly ="readonly">
                </div>
            </div>
            <div class="row">
                <div class="col-sm-3">
                    <label class="col-sm-12">Summary</label>
                    <textarea class="form-control" cols =" 45" rows ="5" readonly ="readonly">@Html.DisplayFor(model => model.Summary)</textarea>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-3">
                    <label class="col-sm-12">Message</label>
                    <input type="text" class="form-control" value="@Html.DisplayFor(model => model.Message)"  readonly ="readonly">
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 m-t-30">    
                    <button type="submit" class="btn btn-info waves-effect waves-light m-r-10">Delete</button>
                </div>
            </div>   
            <p>
            @Html.ActionLink("Back to List", "Index")
            </p>
            }
        @*</form>*@
         <br/>         
	  </div>
   </div>
</div>

    <script>
    $(document).ready(function(){
        $("#manual-in-out2").addClass('collapse in');
        $("#manual-in-out7").addClass('collapse in');

    	$("#err-id").addClass('active');
    });
    </script>

MetlifeAdminPanel/Views/ErrorList/Details.cshtml
@model MetlifeAdminPanel.ErrorList

@{
    ViewBag.Title = "Error Details";
}

<div class="row">
    <div class="col-sm-12">
        <div class="white-box">
            @if (TempData["failed"] != null)
            {
                <img src="~/Content/my_style/plugins/images/failed.jpg" width="30" height="30">
                <span style="color: red; font-size: large;" role="alert">
                    @TempData["failed"]
                </span>
                <br />
            }
            @if (TempData["success"] != null)
            {
                <img src="~/Content/my_style/plugins/images/ok.jpg" width="50" height="50">
                <span style="color: green; font-size: large;" role="alert">
                    @TempData["success"]
                </span>
                <br />				
            }

            @using (Html.BeginForm("Details", "ErrorList", FormMethod.Post, new { autocomplete = "off", enctype = "multipart/form-data", @class = "form-material form-horizontal m-t-30" }))
            {
                @Html.AntiForgeryToken()
            @*<form action="#" method="post" class="form-material form-horizontal m-t-30">*@ 
                <div class="row">
                    <div class="col-sm-3">
                        <label class="col-sm-12">Error Code</label>
                        <input type="text" class="form-control" value="@Html.DisplayFor(model => model.ErrorCode)" readonly ="readonly" >
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-3">
                        <label class="col-sm-12">Summary</label>
                        <textarea class="form-control" cols=" 45" rows="5" readonly="readonly">@Html.DisplayFor(model => model.Summary)</textarea>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-3">
                        <label class="col-sm-12">Message</label>
                        <input type="text" class="form-control" value="@Html.DisplayFor(model => model.Message)" readonly ="readonly" >
                    </div>
                </div>
            }
            @*</form>*@
            <br />
            <h4>
                @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id = Model.Id }) |
            @Html.ActionLink("Back to List", "Index")
            </h4>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $("#manual-in-out2").addClass('collapse in');
        $("#manual-in-out7").addClass('collapse in');

        $("#err-id").addClass('active');
    });
</script>

MetlifeAdminPanel/Views/ErrorList/Edit.cshtml
@model MetlifeAdminPanel.ErrorList

@{
    ViewBag.Title = "Edit Error";
}


<div class="row">					
	<div class="col-sm-12">
            <div class="white-box">
           @if(TempData["failed"] != null)
           {
			    <img src="~/Content/my_style/plugins/images/failed.jpg" width="30" height="30">
			    <span  style="color: red; font-size:large; "  role="alert" >
					    @TempData["failed"]						
			    </span>
			    <br/>
		    }									 
		    @if(TempData["success"] != null)
            {
			    <img src="~/Content/my_style/plugins/images/ok.jpg" width="50" height="50">
			    <span  style="color: green; font-size:large;"  role="alert" >
					    @TempData["success"] 							
			    </span>
			    <br/>				
		    }  

            @using (Html.BeginForm("Edit", "ErrorList", FormMethod.Post, new { autocomplete = "off", enctype = "multipart/form-data", @class = "form-material form-horizontal m-t-30" }))
            {
                @Html.AntiForgeryToken()
                @*<form action="#" method="post" class="form-material form-horizontal m-t-30"> *@
                    @Html.HiddenFor(model => model.Id)
                <div class="row">
                    <div class="col-sm-3">
                        <label class="col-sm-12">Error Code</label>                        
                        <input type="text" class="form-control"   name ="ErrorCode" value="@Html.DisplayFor(model => model.ErrorCode)">
                    </div>
                 </div> 
                 <div class="row">
                       <div class="col-sm-3">
                        <label class="col-sm-12">Summary</label>
                        <textarea class="form-control" cols =" 45" rows ="5"  name ="Summary" >@Html.DisplayFor(model => model.Summary)</textarea>
                    </div>
                </div> 
                <div class="row">
                    <div class="col-sm-3">
                        <label class="col-sm-12">Message</label>                        
                        <input type="text" class="form-control"   name ="Message" value="@Html.DisplayFor(model => model.Message)">
                    </div>
                 </div>
                <div class="row">
                      <div class="col-md-12 m-t-30">    
                        <button type="submit" class="btn btn-info waves-effect waves-light m-r-10">Update</button>
                      </div>
                  </div>   
                 }  
                @*</form>*@
                 <br/>         
                <h4>               
                @Html.ActionLink("Back to List", "Index")
                </h4>
   		</div>
   	</div>
</div>		



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
    <script>
    $(document).ready(function(){
        $("#manual-in-out2").addClass('collapse in');
        $("#manual-in-out7").addClass('collapse in');

    	$("#err-id").addClass('active');
    });
    </script> 

MetlifeAdminPanel/Views/ErrorList/Index.cshtml
@model IEnumerable<MetlifeAdminPanel.ErrorList>

@{
    ViewBag.Title = "Errors";
}

<div class="col-sm-12">
  <div class="white-box">      
           @if(TempData["failed"] != null)
           {
			    <img src="~/Content/my_style/plugins/images/failed.jpg" width="30" height="30">
			    <span  style="color: red; font-size:large; "  role="alert" >
					    @TempData["failed"]						
			    </span>
			    <br/>
		    }									 
		    @if(TempData["success"] != null)
            {
			    <img src="~/Content/my_style/plugins/images/ok.jpg" width="50" height="50">
			    <span  style="color: green; font-size:large;"  role="alert" >
					    @TempData["success"] 							
			    </span>
			    <br/>				
		    }  
      <div class="table-responsive">
			<table id="example5" class="table display">
                <thead>
				<tr>
                    <th>
                       Error Code
                    </th>
                    <th>
                        Message
                    </th>    
                    <th style="width: 60px;">
                        Action
                    </th>                                     
				</tr>
				</thead>	
				<tbody>
                   @{ var status = "Active";}
                   @foreach (var item in Model) {
                    <tr>
                        <td>
                            @Html.ActionLink(@item.ErrorCode, "Details", new { id=item.Id }) 
                        </td>
                        <td>
                            @Html.ActionLink(@item.Message, "Details", new { id=item.Id }) 
                        </td> 
                        <td>
                            <a class="btn btn-primary btn-xs"   data-toggle="tooltip" title="Edit" data-placement="top" href="Edit/@item.Id" >
                                    <span class="fa fa-pencil"></span>
                            </a>
                            <a class="btn btn-danger btn-xs"   data-toggle="tooltip" title="Delete" data-placement="top" href="Delete/@item.Id" >
                                    <span class="fa fa-trash"></span>
                            </a>
                        </td>                                  
                    </tr>
                    }
				</tbody>
			</table>
            <br/>
            <h4 style="margin-left: 5px;">To Create New Error @Html.ActionLink("click here", "Create")</h4>
		 </div>
      </div>
  </div>



    <script>
        $(document).ready(function () {
            $("#manual-in-out2").addClass('collapse in');
            $("#manual-in-out7").addClass('collapse in');

            $("#err-id").addClass('active');
        });
    </script> 