MetlifeAdminPanel/Controllers/ECollectionController.cs
using MetlifeAdminPanel.Services;
using RKLib.ExportData;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MetlifeAdminPanel.Controllers
{
    public class ECollectionController : Controller
    {
        List<DisplayTable> listPayingBank = DBContext.GetPayingBankList();
        public static string downloadedFileName = "";
        
        //for publish
        //string path = "Downloaded/Ecollection/";

        //for test
        string path = AppDomain.CurrentDomain.BaseDirectory + "/Downloaded/Ecollection/";
        
        // GET: /ECollection Report/Search
        public ActionResult Search()
        {
            if (!DBContext.hasPermission("Metlife E-Collection Report"))
            {
                return RedirectToAction("Action", "Error");
            }
            else
            {
                EcollectionManager reportManager = new EcollectionManager();
                reportManager.dummySearch.DropDownListForECollectionBank = new SelectList(listPayingBank, "Key", "Display");
                return View(reportManager);
            }
        }

        // POST: /Report/Search
        [HttpPost]
        public ActionResult Search(EcollectionManager reportManager)
        {
            if (!DBContext.hasPermission("Metlife E-Collection Report"))
            {
                return RedirectToAction("Action", "Error");
            }
            else
            {
                List<ECollection> list = DBContext.GetEcollectionList(reportManager);
                reportManager.tranList = list;
                reportManager.dummySearch.DropDownListForECollectionBank = new SelectList(listPayingBank, "Key", "Display");

                return View(reportManager);
            }
        }


        // GET: /Report/Search
        public ActionResult Download()
        {
            if (!DBContext.hasPermission("Metlife E-Collection Report"))
            {
                return RedirectToAction("Action", "Error");
            }
            else
            {
                EcollectionManager reportManager = new EcollectionManager();
                reportManager.dummySearch.DropDownListForECollectionBank = new SelectList(listPayingBank, "Key", "Display");
                return RedirectToAction("search");
                //return View("search", reportManager);
            }
        }
        private OLPABDDATAEntities_new db = new OLPABDDATAEntities_new();

        // POST: /Report/Search
        [HttpPost]
        public ActionResult Download(EcollectionManager reportManager)
        {

            if (!DBContext.hasPermission("Metlife E-Collection Report"))
            {
                return RedirectToAction("Action", "Error");
            }
            else
            {
                List<ECollection> list = DBContext.GetEcollectionList(reportManager);
                reportManager.tranList = list;
                reportManager.dummySearch.DropDownListForECollectionBank = new SelectList(listPayingBank, "Key", "Display");
                List<ExcelDatForEcollection> list2 = new List<ExcelDatForEcollection>();
                foreach (ECollection trn in list)
                {
                    ExcelDatForEcollection trn2 = new ExcelDatForEcollection();
                    trn2.Orderid = trn.OrderID;
                    trn2.beneficiaryName = trn.BeneficiaryName;
                    trn2.bankAccountNumber = trn.BankAccountNumber;
                    trn2.payingBank = DBContext.GetEcollectionBankById(trn.PayingBank).Replace("\r\n", string.Empty).ToString();

                    trn2.bankName = trn.BankName;
                    trn2.branch = trn.Branch;
                    trn2.Amount = trn.Amount;
                    list2.Add(trn2);
                }
                try
                {
                    DataSet dataSet = ReportManager.ListToDataSet(list2);
                    DataTable dtReport = dataSet.Tables["Table1"].Copy();
                    RKLib.ExportData.Export objExport = new RKLib.ExportData.Export("Win");

                    downloadedFileName = "Metlife_Ecollection_Report_" + DateTime.Now.Year + DateTime.Now.Month + DateTime.Now.Day + DateTime.Now.Hour + DateTime.Now.Minute + DateTime.Now.Second + DateTime.Now.Millisecond + ".xls";
                    objExport.ExportDetails(dtReport, Export.ExportFormat.Excel, path + downloadedFileName);
                    return RedirectToAction("DownloadFile", new { fileName = downloadedFileName });

                }
                catch (Exception Ex)
                {
                }
                return View("search", reportManager);
            }
        }


        public ActionResult DownloadFile(string fileName)
        {
            byte[] fileBytes = System.IO.File.ReadAllBytes(path + fileName);
            ModelState.AddModelError("Success", "Downloaded successfully");
            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
        }


    }
}

MetlifeAdminPanel/Views/Ecollection/Search.cshtml
@model MetlifeAdminPanel.Services.EcollectionManager

@{
    ViewBag.Title = "Search";
}
<div class="row">					
	<div class="col-sm-12">
        <div class="white-box">
           @if(TempData["failed"] != null)
           {
			    <img src="~/Content/my_style/plugins/images/failed.jpg" width="30" height="30">
			    <span  style="color: red; font-size:large; "  role="alert" >
					    @TempData["failed"]						
			    </span>
			    <br/>
		    }									 
		    @if(TempData["success"] != null)
            {
			    <img src="~/Content/my_style/plugins/images/ok.jpg" width="50" height="50">
			    <span  style="color: green; font-size:large;"  role="alert" >
					    @TempData["success"] 							
			    </span>
			    <br/>				
		    }  

                @using (Html.BeginForm("Search", "ECollection", FormMethod.Post, new { autocomplete = "off", enctype = "multipart/form-data", @class = "form-material form-horizontal m-t-30", @id = "search-form" }))
                {
                    @Html.AntiForgeryToken()
            @*<form action="/ECollection/Search" method="post" class="form-material form-horizontal m-t-30" id="search-form">*@
                @Html.ValidationSummary(true)
                   <div class="row">
                      <div class="col-md-3">
                        <label class="col-sm-12">Order ID</label>
                         <input type="text" class="form-control" name ="dummySearch.orderId" value="@Model.dummySearch.orderId">      
                             @Html.ValidationMessageFor(model => model.dummySearch.orderId)                   
                      </div>
                      <div class="col-md-3">
                        <label class="col-sm-12">Beneficiary Name</label>
                         <input type="text" class="form-control" name ="dummySearch.beneficiaryName" value="@Model.dummySearch.beneficiaryName">      
                             @Html.ValidationMessageFor(model => model.dummySearch.beneficiaryName)                   
                      </div>
                      <div class="col-md-3">
                        <label class="col-sm-12">Bank A/C Number</label>
                             <input type="text" class="form-control" name ="dummySearch.bankAccountNumber" value="@Model.dummySearch.bankAccountNumber">      
                             @Html.ValidationMessageFor(model => model.dummySearch.bankAccountNumber)                   
                      </div>
                  </div>
                  <div class="row">
                      <div class="col-md-3">
                        <label class="col-sm-12">Paying Bank</label>
                            @Html.DropDownListFor(model => model.dummySearch.payingBank, Model.dummySearch.DropDownListForECollectionBank,"Select a Bank Name", new { @class="form-control"})   
                      </div>
                      <div class="col-md-3">
                        <label class="col-sm-12">From Amount</label>
                         <input type="text" class="form-control" name ="dummySearch.fromAmount" value="@Model.dummySearch.fromAmount">      
                             @Html.ValidationMessageFor(model => model.dummySearch.fromAmount)                   
                      </div>
                      <div class="col-md-3">
                        <label class="col-sm-12">To Amount</label>
                        <input type="text" class="form-control" name ="dummySearch.toAmount" value="@Model.dummySearch.toAmount"> 
                          @Html.ValidationMessageFor(model => model.dummySearch.toAmount) 
                      </div>
                  </div>
                  <div class="row">
                      <div class="col-md-12 m-t-30">        
                        <button type="submit" class="btn btn-info waves-effect waves-light m-r-10">Search</button>
                        @*<input type="reset" class="btn btn-secondary "value="Reset">*@
                      </div>
                  </div>
                }
            @*</form>*@
            @if (Model.tranList != null) 
            {
                if (Model.tranList.Count > 0)
                {   
	             <div class="col-sm-12">
                     <div class="white-box">
                          <div class="table-responsive">
			                    <table id="example" class="table display">
                                    <thead>
				                    <tr>
                                        <th>
                                            Order ID
                                        </th>
                                        <th>
                                            Benificiary Name
                                        </th>
                                        <th>
                                            Bank A/C Number
                                        </th>
                                        <th>
                                            Paying Bank
                                        </th>
                                        <th>
                                            Amount
                                        </th>
                                        <th>
                                            Bank Name
                                        </th>
                                        <th>
                                            Branch
                                        </th>
                                    </tr>
				                    </thead>	
				                    <tbody>
                                       @foreach (var item in Model.tranList)
                                       {
                                        <tr>
                                            <td>
                                                @item.OrderID 
                                            </td>
                                            <td>
                                                @item.BeneficiaryName 
                                            </td>
                                            <td>
                                                @item.BankAccountNumber
                                            </td>
                                            <td>
                                                @*@item.PayingBank*@
                                                @MetlifeAdminPanel.Services.DBContext.GetEcollectionBankById(item.PayingBank).ToString()
                                                
                                            </td>
                                            <td>
                                                @item.Amount.ToString()
                                            </td>
                                            <td>
                                                @item.BankName
                                            </td>                                                                                         
                                            <td>
                                                @item.Branch                                                
                                            </td>                              
                                        </tr>
                                       }
				                     </tbody>
			                       </table>
                                </div>
                                <br/>

                                 @using (Html.BeginForm("Download", "ECollection", FormMethod.Post, new { autocomplete = "off", enctype = "multipart/form-data", @class = "form-material form-horizontal m-t-30"}))
                                 {
                                        @Html.AntiForgeryToken()
                                @*<form action="/ECollection/Download" method="post" class="form-material form-horizontal m-t-30">*@
                                    <input type="hidden" name ="dummySearch.orderId" value="@Model.dummySearch.orderId">      
                                    <input type="hidden" name ="dummySearch.beneficiaryName" value="@Model.dummySearch.beneficiaryName">    
                                    <input type="hidden" name ="dummySearch.bankAccountNumber" value="@Model.dummySearch.bankAccountNumber">  
                                    <input type="hidden" name ="dummySearch.payingBank" value="@Model.dummySearch.payingBank"> 
						            <input type="hidden" name ="dummySearch.fromAmount" value="@Model.dummySearch.fromAmount"> 
                                    <input type="hidden" name= "dummySearch.toAmount" value="@Model.dummySearch.toAmount">

                                    <div class="row">
                                        <div class="col-md-12 m-t-30"> 
                                                <button type="submit" class="btn btn-info waves-effect waves-light m-r-10">Download Excel</button>
                                        </div>
                                        <br/>

                                        @if (Html.ValidationMessage("Error") != null)
                                        {
								            <span  style="color: red; font-size:large; "  role="alert" >
										            @Html.ValidationMessage("Error")									
								            </span>
								        }									 
								        @if (Html.ValidationMessage("Success")!=null)
                                        {
									        <span  style="color: green; font-size:large;"  role="alert" >
											        @Html.ValidationMessage("Success")								
									        </span>				
								        }		
                                    </div>  
                                 } 
                                @*</form>*@
		                     
                         </div>
                    </div> 
                

  
                }else{
                        <p>No Data Found</p>
                }

            }
        </div>
    </div>
</div>

<script>
    jQuery(document).ready(function () {
        $("#manual-in-out2").addClass('collapse in');
        $("#manual-in-out6").addClass('collapse in');

        $("#e-report-id").addClass('active');
    });
</script>